version: '3'

volumes:
  app-dist: {}

services:
  app:
    build: .
    volumes:
      - app-dist:/home/node/app/dist
    links:
      - mongodb:database
  mongodb:
    image: mongo:4
    restart: always
    volumes:
      - /app/prelauncher/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mantra
      MONGO_INITDB_ROOT_PASSWORD: MantraStart2019!
  nginx:
    image: nginx:1.15-alpine
    ports:
      - '8080:80'
    volumes:
      - /app/nginx:/etc/nginx/conf.d
      - app-dist:/var/www/html
